### ISSUE TITLE
479-largest-palindrome-product.js

### ISSUE THREAD

**Issue by yanickxia** [zhufuge/alg-js#2]
这题貌似JS无解，不知道为什么会算的那么慢···

**Comment by zhufuge** [comment]
慢，不代表无解吧。

以下两种方法都可以得到解，但是就是不能在特定时间内得到。
1.  从两个n位数能相乘得到的最大数（即2n位数的最大数）开始，一个个数从大到小，找到的第一个回文数且该数能因式分解。判断回文数和因式分解开销巨大，最主要的开销还是需要判断的数过于庞大。
2.  从两个n位数本身入手，如两位数中 99*99 最大，到 99*98，到 98*98， 到 99*97 ... 找出其中顺序的规律，然后从乘积中找到第一个回文数。判断回文数开销大，最主要的也是需要判断的数太多。

在该题讨论中的 [Java Solution using assumed max palindrom](https://leetcode.com/problems/largest-palindrome-product/discuss/96297/Java-Solution-using-assumed-max-palindrom) , 使用了构造回文数，再尝试因式分解，来获得答案。这个方法很快。

但是，这个解法对于 JS 等动态语言来说，不一定能得到正确答案，因为动态语言存在数值存储精度问题。就像算 `12345678900987654321` 会存储为 `12345678900987654000` ，从而使得计算出现误差。

**Comment by yanickxia** [comment]
我也是因为一个学妹在用JS刷，这道Easy的题目如果这么搞的确超过了Easy的难度。不太友好倒是。
